// Great daily games that rely on media, live data or crowds, so they stay as links.
export const LINKS = [
  ["krillion", "Krillion", "https://krillion.io/", "Trivia where rare answers dive deeper."],
  ["geoguessr", "GeoGuessr Daily", "https://www.geoguessr.com/daily-challenges", "The daily Street View challenge."],
  ["framed", "Framed", "https://framed.wtf/", "Name the film from six frames."],
  ["moviedle", "Moviedle", "https://moviedle.app/", "A whole film squeezed into one second."],
  ["bandle", "Bandle", "https://bandle.app/", "A song, one instrument at a time."],
  ["spotle", "Spotle", "https://spotle.io/", "Guess the music artist."],
  ["songless", "SongLess", "https://lessgames.com/songless", "Name the song from a snippet."],
  ["gamedle", "Gamedle", "https://www.gamedle.wtf/", "Guess the video game."],
  ["foodguessr", "FoodGuessr", "https://www.foodguessr.com/", "Where in the world is this dish from?"],
  ["timeguessr", "TimeGuessr", "https://timeguessr.com/", "When and where was this photo taken?"],
  ["whentaken", "WhenTaken", "https://whentaken.com/", "Date the photo, drop the pin."],
  ["wheretaken", "WhereTaken", "https://wheretaken.teuteuf.fr/", "Find the place in the picture."],
  ["chronophoto", "Chronophoto", "https://www.chronophoto.app/daily.html", "Which year is this photo from?"],
  ["tradle", "Tradle", "https://oec.world/en/games/tradle", "Guess the country from its exports."],
  ["flagle", "Flagle", "https://www.flagle.io/", "Reveal the flag tile by tile."],
  ["semantle", "Semantle", "https://semantle.com/", "Find the word by meaning."],
  ["contexto", "Contexto", "https://contexto.me/", "Guess the secret word by context."],
  ["murdle", "Murdle", "https://murdle.com/", "Deduce the murderer, weapon and place."],
  ["cluesbysam", "Clues by Sam", "https://cluesbysam.com/", "Who is criminal, who is innocent?"],
  ["catfishing", "Catfishing", "https://catfishing.net/", "Guess the article from its categories."],
  ["redactle", "Redactle", "https://redactle.net/", "Uncover a blacked-out encyclopedia page."],
  ["metazooa", "Metazooa", "https://metazooa.com/", "Find the animal on the tree of life."],
  ["metaflora", "Metaflora", "https://flora.metazooa.com/", "Same idea, with plants."],
  ["pokedle", "Pokedle", "https://pokedle.net/", "Guess today's Pokémon."],
  ["loldle", "LoLdle", "https://loldle.net/", "Guess the League champion."],
  ["poeltl", "Poeltl", "https://poeltl.nbpa.com/", "Guess the NBA player."],
  ["costcodle", "Costcodle", "https://costcodle.com/", "Guess the price of a warehouse item."],
  ["immaculate", "Immaculate Grid", "https://www.sports-reference.com/immaculate-grid/", "Baseball trivia noughts and crosses."],
  ["puzzmo", "Puzzmo", "https://www.puzzmo.com/", "A daily bundle of fresh puzzles."],
  ["bracketcity", "Bracket City", "https://www.theatlantic.com/games/bracket-city/", "Solve clues nested inside clues."],
  ["guardianquick", "Guardian Quick", "https://www.theguardian.com/crosswords/series/quick", "The classic quick crossword."],
];
