// Daily puzzle catalog. Each entry: id, name, url, category, emoji, color, blurb.
const GAMES = [
  // Words
  { id: "wordle", name: "Wordle", url: "https://www.nytimes.com/games/wordle/index.html", cat: "Words", emoji: "🟩", color: "#6aaa64", blurb: "Guess the five-letter word in six tries." },
  { id: "connections", name: "Connections", url: "https://www.nytimes.com/games/connections", cat: "Words", emoji: "🔗", color: "#b9a0e8", blurb: "Sort 16 words into four hidden groups." },
  { id: "strands", name: "Strands", url: "https://www.nytimes.com/games/strands", cat: "Words", emoji: "🧵", color: "#c0ddd9", blurb: "Find the theme words hidden in the grid." },
  { id: "spellingbee", name: "Spelling Bee", url: "https://www.nytimes.com/puzzles/spelling-bee", cat: "Words", emoji: "🐝", color: "#f7da21", blurb: "Make words from seven letters." },
  { id: "nytmini", name: "The Mini", url: "https://www.nytimes.com/crosswords/game/mini", cat: "Words", emoji: "✏️", color: "#4f85e5", blurb: "A tiny crossword for a quick win." },
  { id: "letterboxed", name: "Letter Boxed", url: "https://www.nytimes.com/puzzles/letter-boxed", cat: "Words", emoji: "🔲", color: "#fc716b", blurb: "Use every letter around the square." },
  { id: "quordle", name: "Quordle", url: "https://www.merriam-webster.com/games/quordle/", cat: "Words", emoji: "4️⃣", color: "#305a9b", blurb: "Four Wordles at once, nine guesses." },
  { id: "octordle", name: "Octordle", url: "https://octordle.com/", cat: "Words", emoji: "8️⃣", color: "#e67e22", blurb: "Eight words, thirteen guesses." },
  { id: "sedecordle", name: "Sedecordle", url: "https://www.sedecordle.com/", cat: "Words", emoji: "🔢", color: "#8e44ad", blurb: "Sixteen Wordles in one board." },
  { id: "duotrigordle", name: "Duotrigordle", url: "https://duotrigordle.com/", cat: "Words", emoji: "🌀", color: "#16a085", blurb: "Thirty-two words. Pure chaos." },
  { id: "waffle", name: "Waffle", url: "https://wafflegame.net/daily", cat: "Words", emoji: "🧇", color: "#e0a83a", blurb: "Swap letters to fix the waffle grid." },
  { id: "squaredle", name: "Squaredle", url: "https://squaredle.app/", cat: "Words", emoji: "🔠", color: "#3d6fd1", blurb: "Trace words through a letter grid." },
  { id: "semantle", name: "Semantle", url: "https://semantle.com/", cat: "Words", emoji: "🧠", color: "#5d6d7e", blurb: "Find the word by meaning, not spelling." },
  { id: "contexto", name: "Contexto", url: "https://contexto.me/", cat: "Words", emoji: "🎯", color: "#2c3e50", blurb: "Guess the secret word by context." },
  { id: "6mal5", name: "6mal5", url: "https://6mal5.com/", cat: "Words", emoji: "🇩🇪", color: "#d35400", blurb: "Wordle auf Deutsch." },
  { id: "phrazle", name: "Phrazle", url: "https://solitaired.com/phrazle", cat: "Words", emoji: "💬", color: "#27ae60", blurb: "Guess the hidden phrase." },
  { id: "wordiply", name: "Wordiply", url: "https://www.wordiply.com/", cat: "Words", emoji: "➕", color: "#1abc9c", blurb: "Build the longest word around a seed." },
  { id: "weaver", name: "Weaver", url: "https://wordwormdormdork.com/", cat: "Words", emoji: "🪜", color: "#7f8c8d", blurb: "Ladder from one word to another." },
  { id: "redactle", name: "Redactle", url: "https://redactle.net/", cat: "Words", emoji: "⬛", color: "#34495e", blurb: "Uncover the hidden Wikipedia article." },
  { id: "raddle", name: "Raddle", url: "https://raddle.quest/", cat: "Words", emoji: "🗝️", color: "#b03a2e", blurb: "Climb a word ladder with clues." },
  { id: "blossom", name: "Blossom", url: "https://www.merriam-webster.com/games/blossom-word-game", cat: "Words", emoji: "🌸", color: "#f5a3c7", blurb: "Score big with seven petal letters." },
  { id: "keyword", name: "Keyword", url: "https://www.washingtonpost.com/games/keyword/", cat: "Words", emoji: "🔑", color: "#222222", blurb: "Crack the vertical keyword." },
  { id: "bracketcity", name: "Bracket City", url: "https://www.theatlantic.com/games/bracket-city/", cat: "Words", emoji: "🏙️", color: "#e74c3c", blurb: "Solve nested bracket clues." },
  { id: "guardianquick", name: "Guardian Quick", url: "https://www.theguardian.com/crosswords/series/quick", cat: "Words", emoji: "📰", color: "#052962", blurb: "The classic quick crossword." },

  // Logic & Numbers
  { id: "pips", name: "Pips", url: "https://www.nytimes.com/games/pips", cat: "Logic", emoji: "🎲", color: "#c86fc9", blurb: "Place dominoes to satisfy the regions." },
  { id: "nytsudoku", name: "NYT Sudoku", url: "https://www.nytimes.com/puzzles/sudoku", cat: "Logic", emoji: "9️⃣", color: "#f58f3a", blurb: "Easy, medium or hard, every day." },
  { id: "tiles", name: "Tiles", url: "https://www.nytimes.com/puzzles/tiles", cat: "Logic", emoji: "🎨", color: "#a0c4b8", blurb: "Match patterns in a calm combo chain." },
  { id: "queens", name: "Queens", url: "https://www.linkedin.com/games/queens/", cat: "Logic", emoji: "👑", color: "#a77bd0", blurb: "One queen per row, column and region." },
  { id: "tango", name: "Tango", url: "https://www.linkedin.com/games/tango/", cat: "Logic", emoji: "🌗", color: "#f39c12", blurb: "Balance suns and moons on the grid." },
  { id: "zip", name: "Zip", url: "https://www.linkedin.com/games/zip/", cat: "Logic", emoji: "⚡", color: "#e8590c", blurb: "Draw one path through every cell." },
  { id: "minisudoku", name: "Mini Sudoku", url: "https://www.linkedin.com/games/mini-sudoku/", cat: "Logic", emoji: "🔟", color: "#0a66c2", blurb: "A 6×6 sudoku in a minute." },
  { id: "crossclimb", name: "Crossclimb", url: "https://www.linkedin.com/games/crossclimb/", cat: "Logic", emoji: "🧗", color: "#2e86de", blurb: "Trivia meets word ladder." },
  { id: "pinpoint", name: "Pinpoint", url: "https://www.linkedin.com/games/pinpoint/", cat: "Logic", emoji: "📍", color: "#ee5253", blurb: "Find the category in five clues." },
  { id: "nerdle", name: "Nerdle", url: "https://nerdlegame.com/", cat: "Logic", emoji: "➗", color: "#820458", blurb: "Wordle, but it's an equation." },
  { id: "mathler", name: "Mathler", url: "https://www.mathler.com/", cat: "Logic", emoji: "🧮", color: "#3867d6", blurb: "Find the equation that hits the target." },
  { id: "primel", name: "Primel", url: "https://converged.yt/primel/", cat: "Logic", emoji: "🔣", color: "#20bf6b", blurb: "Guess the five-digit prime." },
  { id: "set", name: "Daily SET", url: "https://www.setgame.com/set/puzzle", cat: "Logic", emoji: "🔺", color: "#8854d0", blurb: "Find all six sets today." },
  { id: "murdle", name: "Murdle", url: "https://murdle.com/", cat: "Logic", emoji: "🔪", color: "#8b0000", blurb: "Solve a murder with deduction grids." },
  { id: "cluesbysam", name: "Clues by Sam", url: "https://cluesbysam.com/", cat: "Logic", emoji: "🕵️", color: "#4b6584", blurb: "Who is criminal, who is innocent?" },
  { id: "puzzmo", name: "Puzzmo", url: "https://www.puzzmo.com/", cat: "Logic", emoji: "🧩", color: "#ff6b6b", blurb: "A daily bundle of fresh puzzles." },
  { id: "hexcodle", name: "Hexcodle", url: "https://hexcodle.com/", cat: "Logic", emoji: "#️⃣", color: "#ff00aa", blurb: "Guess the hex code of a color." },
  { id: "colorfle", name: "Colorfle", url: "https://colorfle.com/", cat: "Logic", emoji: "🎨", color: "#45aaf2", blurb: "Mix the target color." },
  { id: "angle", name: "Angle", url: "https://www.angle.wtf/", cat: "Logic", emoji: "📐", color: "#26de81", blurb: "Guess the angle in four tries." },

  // Trivia & Estimation
  { id: "krillion", name: "Krillion", url: "https://krillion.io/", cat: "Trivia", emoji: "🦐", color: "#0077b6", blurb: "Rare answers dive deeper." },
  { id: "magnitudle", name: "Magnitudle", url: "https://magnitudle.com/", cat: "Trivia", emoji: "📏", color: "#5f27cd", blurb: "Guess the order of magnitude." },
  { id: "catfishing", name: "Catfishing", url: "https://catfishing.net/", cat: "Trivia", emoji: "🐟", color: "#0fb9b1", blurb: "Guess the article from its categories." },
  { id: "immaculategrid", name: "Immaculate Grid", url: "https://www.sports-reference.com/immaculate-grid/", cat: "Trivia", emoji: "⚾", color: "#1e3799", blurb: "Baseball trivia tic-tac-toe." },
  { id: "poeltl", name: "Poeltl", url: "https://poeltl.nbpa.com/", cat: "Trivia", emoji: "🏀", color: "#ee5a24", blurb: "Guess the NBA player." },
  { id: "costcodle", name: "Costcodle", url: "https://costcodle.com/", cat: "Trivia", emoji: "🛒", color: "#e31837", blurb: "Guess the price of a Costco item." },
  { id: "foodguessr", name: "FoodGuessr", url: "https://www.foodguessr.com/", cat: "Trivia", emoji: "🍜", color: "#f0932b", blurb: "Where is this dish from?" },
  { id: "metazooa", name: "Metazooa", url: "https://metazooa.com/", cat: "Trivia", emoji: "🦒", color: "#6ab04c", blurb: "Find the animal via the tree of life." },
  { id: "metaflora", name: "Metaflora", url: "https://flora.metazooa.com/", cat: "Trivia", emoji: "🌿", color: "#2d8a4e", blurb: "Same idea, but plants." },
  { id: "pokedle", name: "Pokedle", url: "https://pokedle.net/", cat: "Trivia", emoji: "⚪", color: "#e3350d", blurb: "Guess today's Pokémon." },
  { id: "loldle", name: "LoLdle", url: "https://loldle.net/", cat: "Trivia", emoji: "⚔️", color: "#c8aa6e", blurb: "Guess the League champion." },

  // Geography & Time
  { id: "worldle", name: "Worldle", url: "https://worldle.teuteuf.fr/", cat: "Geo", emoji: "🗺️", color: "#3498db", blurb: "Identify the country by shape." },
  { id: "globle", name: "Globle", url: "https://globle-game.com/", cat: "Geo", emoji: "🌍", color: "#2ecc71", blurb: "Find the mystery country on a globe." },
  { id: "tradle", name: "Tradle", url: "https://oec.world/en/games/tradle", cat: "Geo", emoji: "📦", color: "#0b8457", blurb: "Guess the country by its exports." },
  { id: "flagle", name: "Flagle", url: "https://www.flagle.io/", cat: "Geo", emoji: "🏳️", color: "#e17055", blurb: "Reveal the flag piece by piece." },
  { id: "travle", name: "Travle", url: "https://travle.earth/", cat: "Geo", emoji: "🧭", color: "#00a8ff", blurb: "Connect two countries by land." },
  { id: "countryle", name: "Countryle", url: "https://countryle.com/", cat: "Geo", emoji: "🌐", color: "#4834d4", blurb: "Narrow the country by stats." },
  { id: "wheretaken", name: "WhereTaken", url: "https://wheretaken.teuteuf.fr/", cat: "Geo", emoji: "📷", color: "#2f3640", blurb: "Where was this photo taken?" },
  { id: "geogrid", name: "GeoGrid", url: "https://www.geogridgame.com/", cat: "Geo", emoji: "🔳", color: "#009432", blurb: "Countries tic-tac-toe." },
  { id: "geoguessr", name: "GeoGuessr Daily", url: "https://www.geoguessr.com/daily-challenges", cat: "Geo", emoji: "📍", color: "#563b9a", blurb: "The daily Street View challenge." },
  { id: "timeguessr", name: "TimeGuessr", url: "https://timeguessr.com/", cat: "Geo", emoji: "⏳", color: "#b33939", blurb: "Guess when and where." },
  { id: "whentaken", name: "WhenTaken", url: "https://whentaken.com/", cat: "Geo", emoji: "🕰️", color: "#a55eea", blurb: "Date the photo, place the pin." },
  { id: "chronophoto", name: "Chronophoto", url: "https://www.chronophoto.app/daily.html", cat: "Geo", emoji: "🖼️", color: "#706fd3", blurb: "Which year is this photo?" },

  // Media
  { id: "framed", name: "Framed", url: "https://framed.wtf/", cat: "Media", emoji: "🎬", color: "#c0392b", blurb: "Name the movie from six frames." },
  { id: "moviedle", name: "Moviedle", url: "https://moviedle.app/", cat: "Media", emoji: "🍿", color: "#e84118", blurb: "A whole movie in one second." },
  { id: "bandle", name: "Bandle", url: "https://bandle.app/", cat: "Media", emoji: "🎸", color: "#f368e0", blurb: "Guess the song instrument by instrument." },
  { id: "spotle", name: "Spotle", url: "https://spotle.io/", cat: "Media", emoji: "🎧", color: "#1db954", blurb: "Guess the Spotify artist." },
  { id: "songless", name: "SongLess", url: "https://lessgames.com/songless", cat: "Media", emoji: "🎵", color: "#ff9f43", blurb: "Name the song from a snippet." },
  { id: "gamedle", name: "Gamedle", url: "https://www.gamedle.wtf/", cat: "Media", emoji: "🎮", color: "#7158e2", blurb: "Guess the video game." },
];
